/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\audifonos.gltf 
Author: Palta Studio (https://sketchfab.com/paltastudio)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/audifonos-de-seguridad-c0b33a7cbd184b82943db196052a0f52
Title: Audífonos de Seguridad
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("Models/audifono/audifonos.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane__0.geometry}
        material={materials["Scene_-_Root"]}
        rotation={[0, 0, Math.PI]}
        scale={100}
      />
      <mesh
        geometry={nodes.Cube__0.geometry}
        material={materials["Scene_-_Root"]}
        position={[-1.278, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.Sphere__0.geometry}
        material={materials["Scene_-_Root"]}
        position={[-172.968, 0, 0]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/audifonos.gltf");
